# Generated by Django 3.1.7 on 2021-04-13 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('accountId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accountAmount', models.IntegerField(default=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('transactionTime', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('transactionAmount', models.IntegerField(default=0)),
                ('transactionMessage', models.CharField(max_length=100, null=True)),
                ('transactionReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='AIUTS.useraccount')),
                ('transactionSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='AIUTS.useraccount')),
            ],
        ),
    ]
