# Generated by Django 3.1.7 on 2021-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIUTS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransaction',
            name='transactionType',
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='transactionStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve')], max_length=20),
        ),
    ]
