# Generated by Django 3.1.7 on 2021-04-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIUTS', '0002_auto_20210415_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='transactionStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve')], default='Pending', max_length=20),
        ),
    ]
