# Generated by Django 3.1.7 on 2021-04-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIUTS', '0003_auto_20210415_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('DepositRequestID', models.AutoField(primary_key=True, serialize=False)),
                ('RequestTime', models.DateTimeField(auto_now_add=True)),
                ('RequestAmount', models.IntegerField(default=100)),
                ('RequestStatus', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve')], default='Pending', max_length=20)),
                ('RequestReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestReceiver', to='AIUTS.useraccount')),
            ],
        ),
    ]
